# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # Ensure the that Python environment is ready
  - name: Initialize the Virtual Environment
    init: |
      virtualenv .venv
      . .venv/bin/activate
      pip install --upgrade pip setuptools
      pip install -Ur requirements.txt
      python ./src/manage.py migrate
      python ./src/manage.py runserver
    command: |
      gp sync-done python-is-ready # an arbitrary tag

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
- port: 8000
  onOpen: open-browser
  visibility: public

vscode:
  extensions:
    - ms-python.python
